# ReputationRecon Environment Setup Script for Windows PowerShell
# This script helps you set up API keys for ReputationRecon

Write-Host "ReputationRecon - API Key Setup" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan
Write-Host ""

# Check if .env file exists
if (Test-Path .env) {
    Write-Host "Found existing .env file" -ForegroundColor Yellow
    $overwrite = Read-Host "Do you want to overwrite it? (y/N)"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Host "Setup cancelled." -ForegroundColor Yellow
        exit
    }
}

Write-Host ""
Write-Host "Enter your API keys (press Enter to skip optional keys):" -ForegroundColor Green
Write-Host ""

# VirusTotal API Key
$vtKey = Read-Host "VirusTotal API Key (optional, get from https://www.virustotal.com/gui/join-us)"
if ([string]::IsNullOrWhiteSpace($vtKey)) {
    $vtKey = ""
}

# Google Gemini API Key
$geminiKey = Read-Host "Google Gemini API Key (REQUIRED, get from https://makersuite.google.com/app/apikey)"
if ([string]::IsNullOrWhiteSpace($geminiKey)) {
    $geminiKey = ""
}

# Create .env file
$envContent = @"
# ReputationRecon API Keys Configuration
# Generated by setup_env.ps1

# VirusTotal API Key
VIRUSTOTAL_API_KEY=$vtKey

# Google Gemini API Key
GEMINI_API_KEY=$geminiKey
"@

$envContent | Out-File -FilePath .env -Encoding utf8

Write-Host ""
Write-Host "✓ .env file created successfully!" -ForegroundColor Green
Write-Host ""

# Ask if user wants to set environment variables for current session
$setSession = Read-Host "Do you want to set these as environment variables for this PowerShell session? (y/N)"
if ($setSession -eq "y" -or $setSession -eq "Y") {
    if (-not [string]::IsNullOrWhiteSpace($vtKey)) {
        $env:VIRUSTOTAL_API_KEY = $vtKey
        Write-Host "✓ VIRUSTOTAL_API_KEY set for this session" -ForegroundColor Green
    }
    if (-not [string]::IsNullOrWhiteSpace($geminiKey)) {
        $env:GEMINI_API_KEY = $geminiKey
        Write-Host "✓ GEMINI_API_KEY set for this session" -ForegroundColor Green
    }
}

Write-Host ""
Write-Host "Note: The .env file will be automatically loaded when you run the application." -ForegroundColor Cyan
Write-Host "For permanent environment variables, set them in Windows System Settings." -ForegroundColor Cyan
Write-Host ""

