#!/bin/bash
# Secure Your App Health Environment Setup Script for Linux/Mac
# This script helps you set up API keys for Secure Your App Health

echo "Secure Your App Health - API Key Setup"
echo "================================"
echo ""

# Check if .env file exists
if [ -f .env ]; then
    echo "Found existing .env file"
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [ "$overwrite" != "y" ] && [ "$overwrite" != "Y" ]; then
        echo "Setup cancelled."
        exit
    fi
fi

echo ""
echo "Enter your API keys (press Enter to skip optional keys):"
echo ""

# VirusTotal API Key
read -p "VirusTotal API Key (optional, get from https://www.virustotal.com/gui/join-us): " vt_key

# Google Gemini API Key
read -p "Google Gemini API Key (REQUIRED, get from https://makersuite.google.com/app/apikey): " gemini_key

# Create .env file
cat > .env << EOF
# Secure Your App Health API Keys Configuration
# Generated by setup_env.sh

# VirusTotal API Key
VIRUSTOTAL_API_KEY=${vt_key:-}

# Google Gemini API Key
GEMINI_API_KEY=${gemini_key:-}
EOF

echo ""
echo "✓ .env file created successfully!"
echo ""

# Ask if user wants to export for current session
read -p "Do you want to export these as environment variables for this session? (y/N): " export_session
if [ "$export_session" = "y" ] || [ "$export_session" = "Y" ]; then
    if [ -n "$vt_key" ]; then
        export VIRUSTOTAL_API_KEY="$vt_key"
        echo "✓ VIRUSTOTAL_API_KEY exported for this session"
    fi
    if [ -n "$gemini_key" ]; then
        export GEMINI_API_KEY="$gemini_key"
        echo "✓ GEMINI_API_KEY exported for this session"
    fi
fi

echo ""
echo "Note: The .env file will be automatically loaded when you run the application."
echo "For permanent environment variables, add them to your ~/.bashrc or ~/.zshrc file."
echo ""

